In [1]:
import torch

def dec2bin_old(num,num_bits=8):
    # format_str="{:08b}"
    binary = "{:b}".format(num & (0xFF))
    return binary  # 输出：11111111

def dec2bin(decimal, num_bits=8):
    if decimal >= 0:
        # 正数的处理
        binary = bin(decimal)[2:]
        binary = binary.zfill(num_bits) if len(binary) < num_bits else binary
    else:
        # 负数的处理
        binary = bin(decimal & int("1"*num_bits, 2))[2:]
    return binary

def Complt2Sourcd(binary):
    #输入一个补码格式的二进制数，返回其十进制
    decimal = int(binary, 2)
    if binary[0] == '1':  # 检查最高位是否为1，表示负数
        decimal -= 2 ** len(binary)  # 计算补码对应的十进制数
    print(decimal)  # 输出：-2
    return decimal

def dec2hex(decimal_value, bit_len=8):
    # 计算所需的位掩码
    bit_mask = (1 << bit_len) - 1
    
    # 计算所需的十六进制字符串长度
    hex_len = (bit_len + 3) // 4  # 每4位表示一个十六进制字符
    
    # 将带符号的十进制转换为不带符号补码表示的十六进制
    hex_value = format(decimal_value & bit_mask, f'0{hex_len}X')
    
    print(hex_value)  # 输出不带符号补码表示的十六进制值
    return hex_value
# 示例调用
print(dec2hex(-2719, 8))   
print(dec2hex(-2719, 16))  
print(dec2hex(-2719, 32))  
print(dec2hex(-2719, 64))  
    
print(dec2bin_old(-1))
print(dec2bin(-1,16))
print(Complt2Sourcd(dec2bin(-1)))

61
61
F561
F561
FFFFF561
FFFFF561
FFFFFFFFFFFFF561
FFFFFFFFFFFFF561
11111111
1111111111111111
-1
-1


In [2]:
print(Complt2Sourcd("10000000"))

-128
-128


In [6]:
1

[1, 2, 3]

In [22]:
#保存变量
import pickle
import torch
def save_variable(v,filename):
  f=open(filename,'wb')          #打开或创建名叫filename的文档。
  pickle.dump(v,f)               #在文件filename中写入v
  f.close()                      #关闭文件，释放内存。
  return filename

def load_variavle(filename):
  try:
    f=open(filename,'rb+')
    r=pickle.load(f)
    f.close()
    return r
  except EOFError:
    return ""


tensor([[[[ -49,   26,  -81,  ...,  -84,   21, -114],
          [ 102,   61,  -79,  ...,  124, -103,   62],
          [ -79,   19,  -16,  ...,   36,   31,  -58],
          ...,
          [  24, -118,   36,  ..., -122,   18,  -21],
          [-107,  -80,  -46,  ...,   16,   13,   75],
          [ -73,   39,  -37,  ...,   75,  -33,  -72]],

         [[ -32,   49,    7,  ...,  -87,   72,   48],
          [ -13,   67,  -19,  ...,  -53,   43,  -55],
          [ 113,  -21,  -23,  ...,  -32,   20,   44],
          ...,
          [-104,  -78,  112,  ...,   57,  -97,  -71],
          [ -57,  109,   48,  ...,   61,  -28,   93],
          [ 117,   38,  -63,  ...,   59,   71,    5]],

         [[-108,   61,  -71,  ...,   72,   55,   13],
          [ 116,  115,  -41,  ...,  104,   38,  -56],
          [ -31,  109,  -88,  ...,   22,   -4,   25],
          ...,
          [-121,   95,   76,  ...,   34,   14,  108],
          [  -4,   -2,  -79,  ...,  -63,  -23,  -34],
          [ -50,   89,   94,  ...

In [ ]:
A=torch.randint(-128,127,[1,6,197,197])
B=0.1234
names=["A","B"]
save_variable([A,B,names],"Python")
C=load_variavle("Python")
print(A)
print(B)
print(names)

In [26]:
C=load_variavle("SoftMax_In.pkl")

print(C[0])

tensor([[[[ 15.,   3.,  23.,  ...,  68.,  66.,  65.],
          [ -3.,   0.,   0.,  ...,  -8.,  -7.,  -6.],
          [-10.,  -3., -15.,  ..., -48., -46., -43.],
          ...,
          [ -2.,  -1.,   0.,  ...,  -6.,  -4.,  -5.],
          [ -2.,   0.,   0.,  ...,  -5.,  -5.,  -4.],
          [ -7.,  -3., -10.,  ..., -36., -34., -33.]],

         [[-21., -23., -27.,  ..., -52., -57., -54.],
          [  5.,  10.,  10.,  ...,  10.,  11.,  10.],
          [  6.,  10.,  10.,  ...,  11.,  14.,  14.],
          ...,
          [ -8.,  -9., -11.,  ..., -17., -20., -19.],
          [ -7.,  -7., -11.,  ..., -17., -19., -19.],
          [ -4.,  -2.,  -3.,  ...,  -5.,  -8.,  -6.]],

         [[ -4.,  16.,  21.,  ...,   7.,   5.,  15.],
          [ -1.,  -4.,  -5.,  ...,  -1.,   0.,  -3.],
          [  2.,  -7., -10.,  ...,  -3.,  -2.,  -7.],
          ...,
          [  1.,   1.,  -1.,  ...,   0.,  -2.,   1.],
          [  2.,   2.,   1.,  ...,   0.,  -1.,   1.],
          [  3.,  -3.,  -7.,  ...

In [16]:

A

tensor([[[[-122,  -92,   27,  ...,  -62, -121,  -17],
          [  64,  -63,  101,  ...,  -46, -120,   76],
          [  25,   17,  -96,  ..., -107,   85,   88],
          ...,
          [ -17,  -65,  -33,  ...,   83,  -82,   51],
          [ -12,  -46,   13,  ...,  -14,   -6,  -24],
          [ -59,  121,  -82,  ...,   86,   54,   17]],

         [[ -88,  -11, -102,  ...,   61,  -57, -116],
          [   0,   49,  -29,  ...,   24, -118, -128],
          [ -79,   38,  -28,  ...,   83,   42,  -86],
          ...,
          [ -96, -102,  117,  ...,   46,    6,   86],
          [   4,  -89, -128,  ..., -103,  -32,  101],
          [ 119, -120,  -75,  ...,  100,   25,   33]],

         [[ 109, -103,    0,  ...,   95,  -15,   36],
          [ -71,   83,  -94,  ...,  -85,   20,  -85],
          [  33,   64,   22,  ...,   49,  -33,   87],
          ...,
          [-101,   97,   38,  ...,   84,   13,  -76],
          [  33,  -86,  109,  ...,  -12,   57,   32],
          [  31,   34,  -59,  ...

61
61
F561
F561
FFFFF561
FFFFF561
FFFFFFFFFFFFF561
FFFFFFFFFFFFF561


In [2]:
dec2bin(197)
Complt2Sourcd('0011000')

24


In [9]:
dec2bin(int(1.188e+13))
Complt2Sourcd('010101100111000000111001011100001000000000000')
len('010101100111000000111001011100001000000000000')

11880000000000


46

In [5]:
# ffff00fefe00fffe
Complt2Sourcd(dec2bin(int("fe",16)))

-2


In [25]:
A=torch.randint(-128,127,[1,10])#创建随机tensor
print(A[0][1])

tensor(-80)


In [44]:
import random
import torch

def generate_txt(flattened_data,size,path="generatedTxt.txt",nums=4):
    #flattened_data 是一个一维数据
    with open(path, 'w') as file:
        for i in range(0,size,nums):
            for j in range(i+4-1,i-1,-1):
                print(i,j)
                file.write(dec2hex(flattened_data[j],8))
            file.write("\n")
    file.close()
data=torch.randint(0,10,[16])
print(data)
generate_txt(data,16,"data1.txt")

data = [random.randint(1, 100) for _ in range(16)]
print(data)
generate_txt(data,16,"data2.txt")

tensor([6, 8, 5, 3, 0, 8, 3, 7, 2, 1, 0, 7, 3, 5, 5, 1])
0 3
03
0 2
05
0 1
08
0 0
06
4 7
07
4 6
03
4 5
08
4 4
00
8 11
07
8 10
00
8 9
01
8 8
02
12 15
01
12 14
05
12 13
05
12 12
03
[31, 63, 94, 92, 64, 88, 95, 47, 74, 72, 71, 46, 72, 11, 65, 97]
0 3
5C
0 2
5E
0 1
3F
0 0
1F
4 7
2F
4 6
5F
4 5
58
4 4
40
8 11
2E
8 10
47
8 9
48
8 8
4A
12 15
61
12 14
41
12 13
0B
12 12
48


In [32]:
for i in range(0,29,2):
    print(i)

0
2
4
6
8
10
12
14
16
18
20
22
24
26
28


In [22]:
a=dec2hex(torch.tensor(10))
import os

current_directory = os.getcwd()
print(f"Current Directory: {current_directory}")

0000000A
Current Directory: /home/dy/IC_Learning/IC/Softmax
