# randome测试
实际项目中发现一个很严重的问题：\
首先numpy.random.seed(12345),然后创建一个class,在这个class中有一个函数funA，这个函数funA只做了一次随机，结束运行\
接下来，继续调用这个class中的该函数两次，之前想的是numpy.random.seed(12345)设置的是全局随机值，然鹅实际发现并不是

In [8]:
import numpy as np
np.random.seed(12345)
class myclass:
    def funA():
        print(np.random.randint(0,255,(10,10)))
myclass_instance=myclass
myclass_instance.funA()
print("--"*10)
myclass_instance.funA()

[[226 229  29 129 164 169 254 126 101  34]
 [ 29   1 118 113  59 142 105  91 247 118]
 [208 114 201  11  77 138  81 210 166   7]
 [ 43 231  23  29 184 183  31 189  97  91]
 [ 87  36  64 239 131 252 124 133 143 119]
 [ 75 142 115  81 107 133  34  53 115  72]
 [  5 226 108   5  59  83  12 142 251  80]
 [155  38  88 224 235   5  74  76  22  12]
 [248  62  41 146 178  82 185  46  58  23]
 [149   7  81  63 123   0 218 172 185 142]]
--------------------
[[154 171 158 227  32   3 192   6 194 177]
 [251 124 236  37 200  43  62 214  21  65]
 [224   5 251 232 114 121 190 212 199 121]
 [ 69  45 146 116 200 203 146 133  60 118]
 [ 37 137 108 125 102  65  46 153 171 245]
 [192  77   8 136 146 111 143  90  32 236]
 [114  96  86  69 211  79  98  28 135   4]
 [167 242 131  86  32 245  13  84 193 153]
 [172   5 241 126   2  83 216 176 169 163]
 [  5  51  24 109 233  78  83  61 253 170]]


新的问题，现在我们将random.seed挪到函数内部，在函数内部随机两次，并且在外面调用该函数2次，\
可以发现两次函数调用中，只有第一次随机一致，第二次就不一致了

In [36]:
import numpy as np

class myclass:
    def __init__(self):
        np.random.seed(12345)
    def funA():
        # np.random.seed(12345)
        AA=np.random.randint(0,255,(1,10))if True else np.random.randint(0,255,(1,10))

        BB=np.random.randint(0,255,(1,15))if False else np.random.randint(0,255,(1,15))
        print(AA)
        print(BB)
myclass_instance=myclass
myclass_instance.funA()
print("--"*10)
myclass_instance.funA()

[[181 108  21 120 144 112 234  77 236 122]]
[[ 34 159 142 233 103 107 240 223 139 183 241 214  23   2  11]]
--------------------
[[ 47  36 245 171  33  83  36 242 116   3]]
[[ 28 185  33  18 179  83 166  13  62 250  99  24 153 183 239]]
