In [3]:
import numpy as np
def print_line():
    print("=======================")

In [3]:
import numpy as np

# 示例行向量
row_vector = np.array([1, 2, 3])

# 竖向复制 1024 份
result = np.tile(row_vector, (1024, 1))
print(result)


[[1 2 3]
 [1 2 3]
 [1 2 3]
 ...
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [4]:
A=np.arange(12)
print(A.reshape(3,4))
print_line()
print(A.reshape(3,4,order="F"))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [5]:
A=np.arange(12)
B=A.reshape(3,4)
print(B.reshape(1,-1))
print_line()
print(B.reshape(1,-1,order="F"))

[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
[[ 0  4  8  1  5  9  2  6 10  3  7 11]]


In [11]:
import numpy as np

# 创建一个示例数组
arr = np.arange(20)  # 生成一个包含20个元素的数组

# 获取第10个元素并转换成字符串
element_str = str(arr[9])  # 注意Python的索引从0开始，arr[9]是第10个元素

print(element_str)
print(type(element_str))  # 确认类型是 str


9
<class 'str'>


In [6]:
import numpy as np

# 创建一个示例二维矩阵
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# 指定要删除的列索引，例如删除第 1 列和第 3 列（注意索引从 0 开始）
columns_to_delete = [1, 3]

# 使用 np.delete 删除指定列，axis=1 表示按列删除
new_matrix = np.delete(A, columns_to_delete, axis=1)

print("Original Matrix A:")
print(A)
print("\nNew Matrix with Remaining Columns:")
print(new_matrix)


Original Matrix A:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

New Matrix with Remaining Columns:
[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [7]:
A=np.arange(12)
B=A.reshape(4,3)
print(B)
print(B.flatten(order="C"))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [8]:
import numpy as np

# 构建二维数组
data = [
    [0, 1944, 1, 1945],
    [2, 1946, 3, 1947],
    [4, 1948, 5, 1949],
    [6, 1950, 7, 1951],
    [8, 1952, 9, 1953],
    [10, 1954, 11, 1955],
    [12, 1956, 13, 1957],
    [14, 1958, 15, 1959],
    [16, 1960, 17, 1961],
    [18, 1962, 19, 1963],
    [20, 1964, 21, 1965],
    [22, 1966, 23, 1967]
]

# 将二维数组转换为一维数组
flattened_data = np.array(data).flatten()

print(flattened_data)


[   0 1944    1 1945    2 1946    3 1947    4 1948    5 1949    6 1950
    7 1951    8 1952    9 1953   10 1954   11 1955   12 1956   13 1957
   14 1958   15 1959   16 1960   17 1961   18 1962   19 1963   20 1964
   21 1965   22 1966   23 1967]


In [9]:
import numpy as np

# 假设有一个二维数组
array = np.array([[15, 255, 1024], [4095, 16, 300]])

# 将二维数组写入txt文件，每个值按照04x格式
np.savetxt('output.txt', array, fmt='%04x')


In [10]:
import re

string = "s 123abc"
if re.match(r"^\d", string):
    print("字符串以数字开头")
else:
    print("字符串不以数字开头")


字符串不以数字开头


In [12]:
import numpy as np

# 创建从 0 开始，每次增加 2 的序列
sequence = np.arange(0, 10)  # 可调整结束值 100 为你需要的上限

print(sequence)


[0 1 2 3 4 5 6 7 8 9]


In [11]:
import numpy as np
A=np.arange(2048).reshape(512,-1,order="F")
print(A)
print("-"*128)
A=np.arange(2048).reshape(512,-1,order="C")
print(A)
A=np.delete(A,0,axis=0)
print(A)

[[   0  512 1024 1536]
 [   1  513 1025 1537]
 [   2  514 1026 1538]
 ...
 [ 509 1021 1533 2045]
 [ 510 1022 1534 2046]
 [ 511 1023 1535 2047]]
--------------------------------------------------------------------------------------------------------------------------------
[[   0    1    2    3]
 [   4    5    6    7]
 [   8    9   10   11]
 ...
 [2036 2037 2038 2039]
 [2040 2041 2042 2043]
 [2044 2045 2046 2047]]
[[   4    5    6    7]
 [   8    9   10   11]
 [  12   13   14   15]
 ...
 [2036 2037 2038 2039]
 [2040 2041 2042 2043]
 [2044 2045 2046 2047]]


在 NumPy 中，np.delete() 函数接受多种类型的索引来指定要删除的位置，包括整数、列表、元组和数组。NumPy 的设计非常灵活，<br>允许多种数据类型来表示索引，以提高兼容性和用户操作的方便性。<br>这种灵活性使得索引可以是多种数据结构，比如元组、列表或 NumPy 数组，而其作用效果是一致的。

In [16]:
import numpy as np

def delete_invalid_rows(in_matrix, invalid_row_index):
    # 使用 np.delete() 删除指定索引的行
    return np.delete(in_matrix, invalid_row_index, axis=0)

# 示例
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

invalid_row_index = np.array((1, 3)) # 要删除的行索引
invalid_row_index = np.array([[1], [3]]) # 要删除的行索引
new_matrix = delete_invalid_rows(matrix, invalid_row_index)

print(new_matrix)
# 输出:
# [[1 2 3]
#  [7 8 9]]


[[1 2 3]
 [7 8 9]]


In [20]:
import numpy as np
A=np.arange(10).reshape(-1,1)
print(A.shape)
A=np.delete(A,np.array([3,4,6]))

(10, 1)


In [33]:
np.vstack((np.empty((1,1)),np.arange(10).reshape(-1,1)))

array([[5.e-324],
       [0.e+000],
       [1.e+000],
       [2.e+000],
       [3.e+000],
       [4.e+000],
       [5.e+000],
       [6.e+000],
       [7.e+000],
       [8.e+000],
       [9.e+000]])