# 字符串处理

## 时间处理

In [33]:
import time
def print_info(string):
    time_info=time.strftime("%Y-%m-%d %H:%M:%S",time.localtime())
    print("{:20} {:10} {:50}".format(time_info,"INFO",string))
print_info("123")

2024-11-26 17:51:49  INFO       123                                               


## 字符串输出格式

### 字符串对齐
在Python中，这种表达式是用于格式化输出的代码，通常出现在字符串的格式化中，尤其是在f-strings或format方法中。<br>这里的{:<15}和{:<30}等占位符用于指定数据在输出时的宽度和对齐方式。具体含义如下：

{:<15}：代表左对齐，宽度为15个字符。
{:<30}：代表左对齐，宽度为30个字符。
{:<100}：代表左对齐，宽度为100个字符。

In [34]:
#-----------------------------------------------------------------
#字符串对齐
class str_align:


    # def __init__(self):
        # print("new")
        # self.args=cfg_args()

    def printV1(self):
        seed=1024
        tc_name="12345"
        print('{:<15}{:<30}{:<100}'.format("running", tc_name, str(seed))) 
        print('{:>15}'.format("running")) 
if __name__=="__main__":
    str_align_inst=str_align()
    str_align_inst.printV1()

TypeError: 'str' object is not callable

### 当然py还能居中对齐
在这个示例中：

<br>{:^15} 表示在宽度为15的区域内居中对齐。
<br>{:^30} 表示在宽度为30的区域内居中对齐。
<br>{:^100} 表示在宽度为100的区域内居中对齐。

In [4]:
# 示例代码
print("{:^15}{:^30}{:^100}".format("Name", "Position", "Description"))
print("{:^15}{:^30}{:^100}".format("Alice", "Engineer", "Works on system design and architecture"))
print("{:^15}{:^30}{:^100}".format("Bob", "Data Scientist", "Analyzes data for insights and builds models"))


     Name                 Position                                                       Description                                             
     Alice                Engineer                                         Works on system design and architecture                               
      Bob              Data Scientist                                    Analyzes data for insights and builds models                            


### 字符串按某个符号进行分割

In [5]:
A="123.345"
print(A.split(".")[0])

123


## 字符串列表

In [6]:
A=["a","B","C"]
print(A[1:])
print(A[-1:])#A[-1:] 返回从列表的最后一个元素开始，直到列表结束：["C"]。
print(A[:-1])
# A[1:].upper()
# 将列表从索引1开始的所有元素转换为大写
upper_case_list = [item.upper() for item in A[1:]]
print(upper_case_list)
print(len(A))

['B', 'C']
['C']
['a', 'B']
['B', 'C']
3


In [7]:
B=[]
AAA="12345,234"
print(AAA.startswith("12"))
B.append(AAA)
B.append(AAA)
B.append(AAA)
print(B[1])


True
12345,234


## 字符串进制转换

### 十六进制转十进制

In [8]:
#字符串转10进制时的基数设置
print(int("16",16))
print(int("16"))
# print(int("0x16"))#这样就会报错

22
16


In [9]:
#字符串转数组
addr_list = ["0x11", "0x1A", "0xFF", "0x100"]

# 使用列表推导式，将每个十六进制字符串转换为整数
int_list = [int(addr, 16) for addr in addr_list]

print(int_list)


[17, 26, 255, 256]


In [10]:
A="0x100_0010"
print(int(A,16))

16777232


In [11]:
str_list = ["0x4", "0x10", "10"]

# 转换为整数列表
int_list = [int(s, 16) if s.startswith("0x") or s.startswith("0X") else int(s) for s in str_list]

print(int_list)


[4, 16, 10]


In [12]:
# 原始列表
my_list = ["00", "01", "02"]

# 获取前两个元素
first_two_elements = my_list[:2]

print("前两个元素:", first_two_elements)


前两个元素: ['00', '01']


In [13]:
str="00a11f"
for s in str:
    print(s)
int_list=[int(s,16) for s in str]
print(int_list)

0
0
a
1
1
f
[0, 0, 10, 1, 1, 15]


In [14]:
import numpy as np
str="00a11f"
rim_matrix=[]
for s in str:
    print(s)
int_list=[int(s,16) for s in str]
rim_matrix.append(int_list)
rim_matrix.append(int_list)
rim_matrix.append(int_list)
print(rim_matrix)
rim_matrix=np.array(rim_matrix)
print(rim_matrix)


0
0
a
1
1
f
[[0, 0, 10, 1, 1, 15], [0, 0, 10, 1, 1, 15], [0, 0, 10, 1, 1, 15]]
[[ 0  0 10  1  1 15]
 [ 0  0 10  1  1 15]
 [ 0  0 10  1  1 15]]


In [15]:
s = "001100ff"
A=[]
# 按 8-bit 切分
bit_list = [s[i:i+2] for i in range(0, len(s), 2)]

print(bit_list)


['00', '11', '00', 'ff']


In [16]:
import numpy as np

# 创建两个一维向量
vector1 = np.array([[1, 2, 3]])
vector2 = np.array([[4, 5, 6]])

# 方法 1: 使用 concatenate
# concatenated_vector = np.concatenate((vector1, vector2))

# 方法 2: 使用 hstack
concatenated_vector = np.hstack((vector1[0,:], vector2[0,:]))  # 也可以使用这个方法

print("拼接后的向量:")
print(concatenated_vector)
print(vector2[0,:].shape)

拼接后的向量:
[1 2 3 4 5 6]
(3,)


In [17]:
import numpy as np

# 创建一个 NumPy 数组
array = np.array([[1, 2, 3],
                  [4, 5, 6]])

# 将数组转换为字符串
array_str = np.array2string(array)

print("NumPy 数组的字符串表示:")
print(type(array_str))


NumPy 数组的字符串表示:
<class 'str'>


In [18]:
import numpy as np

# 创建 NumPy 数组
array = np.array([0, 1, 0, 15])

# 将数组元素转换为十六进制字符串，并去掉前缀 "0x"
hex_str = ''.join(format(x, 'x') for x in array)

print("转换后的字符串:", hex_str)


转换后的字符串: 010f


In [19]:
import numpy as np

# 创建一个 2x16 的矩阵
matrix = np.arange(32).reshape(2, 16)  # 示例数据 [0, 1, 2, ..., 31]

# 按列转换为 8x4 的矩阵
reshaped_matrix = matrix.reshape(8, -1, order='F')  # 'F' 表示按列优先

print("2x16 的矩阵:")
print(matrix)

print("\n转换为 8x4 的矩阵:")
print(reshaped_matrix)


2x16 的矩阵:
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]]

转换为 8x4 的矩阵:
[[ 0  4  8 12]
 [16 20 24 28]
 [ 1  5  9 13]
 [17 21 25 29]
 [ 2  6 10 14]
 [18 22 26 30]
 [ 3  7 11 15]
 [19 23 27 31]]


In [20]:
A=np.zeros((10,10))
print(A)
print(A[0,:])
print(len(A))
print(A.shape)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
10
(10, 10)


In [21]:
for i in range(0,10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [22]:
A=np.ones((10,10))*128<127
B=np.ones_like(A)
print(A.shape,B.shape)

(10, 10) (10, 10)


In [23]:
import numpy as np

# 创建一个示例数组
matrix = np.random.rand(5, 4)  # 5 行 4 列的矩阵

# 在每一列后面插入一个空白列
for i in range(matrix.shape[1]):
    matrix = np.insert(matrix, 2 * i + 1, np.zeros(matrix.shape[0]), axis=1)

print("插入空白列后的矩阵：")
print(matrix)


插入空白列后的矩阵：
[[0.95788953 0.         0.53316528 0.         0.69187711 0.
  0.31551563 0.        ]
 [0.68650093 0.         0.83462567 0.         0.01828828 0.
  0.75014431 0.        ]
 [0.98886109 0.         0.74816565 0.         0.28044399 0.
  0.78927933 0.        ]
 [0.10322601 0.         0.44789353 0.         0.9085955  0.
  0.29361415 0.        ]
 [0.28777534 0.         0.13002857 0.         0.01936696 0.
  0.67883553 0.        ]]


In [24]:
import numpy as np

# 创建一个示例矩阵 A
A = np.random.rand(5, 3)  # 5 行 3 列的随机矩阵

# 获取第一列和第二列
first_col = A[:, 0]  # 第一列
second_col = A[:, 1]  # 第二列

# 逐元素相乘
result = first_col * second_col

print("矩阵 A：")
print(A)

print("\n第一列和第二列的逐元素乘积：")
print(result)


矩阵 A：
[[0.21162812 0.26554666 0.49157316]
 [0.05336255 0.57411761 0.14672857]
 [0.58930554 0.69975836 0.10233443]
 [0.41405599 0.69440016 0.41417927]
 [0.04995346 0.53589641 0.66379465]]

第一列和第二列的逐元素乘积：
[0.05619714 0.03063638 0.41237148 0.28752054 0.02676988]


In [25]:
import numpy as np

# 创建一个包含负数的数组
array = np.array([15, -2, 8, -15, 255, -128], dtype=int)

# 将数组中的每个元素转换为十六进制字符串（以补码表示处理负数）
def int_to_hex(num, bits=8):
    if num < 0:
        num = (1 << bits) + num  # 负数使用补码表示
    return f'{num:0{bits//4}x}'  # 十六进制表示

# 将整个数组转化为十六进制
hex_array = [int_to_hex(x, bits=8) for x in array]

# 将十六进制值写入到txt文件
for hex_val in hex_array:
    # f.write(hex_val + '\n')  # 每个十六进制数换行输出
    print(hex_val)
print("十六进制值已写入 output.txt 文件。")


0f
fe
08
f1
ff
80
十六进制值已写入 output.txt 文件。


In [26]:
# 假设 matrix 是一个二维数组 (比如 NumPy 数组)
import numpy as np

# 创建一个示例矩阵
matrix = np.random.rand(1000, 2000)  # 1000 行 2000 列的矩阵

# 提取最后 1944 列
last_1944_columns = matrix[:, -1943:]
print(last_1944_columns.shape)

(1000, 1943)


In [27]:
import numpy as np

# 创建一个示例矩阵
matrix = np.random.rand(3, 5)  # 3 行 5 列的矩阵

# 翻转每一行
flipped_matrix = np.fliplr(matrix)

# 打印原始矩阵和翻转后的矩阵
print("Original matrix:")
print(matrix)

print("\nFlipped matrix:")
print(flipped_matrix)


Original matrix:
[[0.01440308 0.60906415 0.19636861 0.30807383 0.15358408]
 [0.48163243 0.03039629 0.83399961 0.30065084 0.84829827]
 [0.45967237 0.76629044 0.78366559 0.65051559 0.27916523]]

Flipped matrix:
[[0.15358408 0.30807383 0.19636861 0.60906415 0.01440308]
 [0.84829827 0.30065084 0.83399961 0.03039629 0.48163243]
 [0.27916523 0.65051559 0.78366559 0.76629044 0.45967237]]


## 文件处理

### 获取文件名

In [28]:
import os

# 获取用户输入的路径或文件名
input_path ="/BW0l Proj Digital/yao.dai/myscrip/prog tool/die_0_L2_0_L0_0"

# 获取文件名
file_name = os.path.basename(input_path)

# 输出结果
print("文件名:", file_name)


文件名: die_0_L2_0_L0_0


### with open文件读写
会自动创建一个文件，无需手动创建

In [29]:
with open("test_file.txt","a+")as file:
    file.write("hahhah\n")


In [30]:
print(0x20000+1023)

132095


# 获取当前py脚本所在绝对路径

In [31]:
import os

# 当前脚本所在的绝对路径
script_path = os.path.abspath(__file__)
print(f"脚本路径: {script_path}")

# 当前脚本所在的目录
script_dir = os.path.dirname(script_path)
print(f"脚本目录: {script_dir}")

NameError: name '__file__' is not defined

In [3]:
def generate_filelist(path,match=(".sv",".v")):
    #recursily check current dir,and create filelist including every dir that include ".sv"
    directories = []
    # 递归遍历目录
    for dirpath, dirnames, filenames in os.walk(path):
        # 检查当前目录是否有 .sv 文件
        if any(file.endswith(match) for file in filenames):
            directories.append(dirpath)
    return directories        
generate_filelist("/home/dy/IC/Basic/Vip/Official_examples/tb_ahb_svt_uvm_basic_sys")

['/home/dy/IC/Basic/Vip/Official_examples/tb_ahb_svt_uvm_basic_sys',
 '/home/dy/IC/Basic/Vip/Official_examples/tb_ahb_svt_uvm_basic_sys/tests',
 '/home/dy/IC/Basic/Vip/Official_examples/tb_ahb_svt_uvm_basic_sys/env',
 '/home/dy/IC/Basic/Vip/Official_examples/tb_ahb_svt_uvm_basic_sys/hdl_interconnect']

In [22]:
import numpy as np
with open("test.txt","w")as f:
    A=np.arange(10,dtype=np.uint8)+255

    f.write("".join(format(x,"04x") for x in A)+"\n")
    print(format(A[5],"04x"))
print(A)

0004
[255   0   1   2   3   4   5   6   7   8]


In [23]:
import numpy as np

def generate_hex(np_matrix, opt="w"):
    output_path="."
    out_file_name = "test.txt"
    
    print(f"[in bin2hex] generating {output_path}/{out_file_name}...")
    with open(output_path + "/" + out_file_name, opt) as f:
        row_index = 0
        for row in np_matrix:
            f.write(''.join(format(x, "04x") for x in row) + '\n')
if __name__=="__main__":
    np.random.seed(345)
    A=np.random.randint(0,255,size=(10,10),dtype=np.uint8)
    print(A)
    A.dtype=np.int8
    B=np.zeros((10,10),dtype=np.int16)

    # B[:,:]=A
    print(A)
    # generate_hex(B)

[[ 24  14 245  94 208 239   6 178  83 218]
 [ 53 170 207  72 202  71 137 250  36 127]
 [157 193  47 246  42 218  33 154  75 116]
 [ 59 220 152 231 130  62  68  27 218 113]
 [ 29 207 167 126   3 127 228 186   4 250]
 [229 181  42 133 187  30  97 115 142 115]
 [ 23  93 145 211 244 168  10  12  80 232]
 [239 206 201  39 238 135  86 178  70 196]
 [254  51 149 141 147 117 131  97  12 156]
 [ 75  29 248  29 194 234  96 102 215  62]]
[[  24   14  -11   94  -48  -17    6  -78   83  -38]
 [  53  -86  -49   72  -54   71 -119   -6   36  127]
 [ -99  -63   47  -10   42  -38   33 -102   75  116]
 [  59  -36 -104  -25 -126   62   68   27  -38  113]
 [  29  -49  -89  126    3  127  -28  -70    4   -6]
 [ -27  -75   42 -123  -69   30   97  115 -114  115]
 [  23   93 -111  -45  -12  -88   10   12   80  -24]
 [ -17  -50  -55   39  -18 -121   86  -78   70  -60]
 [  -2   51 -107 -115 -109  117 -125   97   12 -100]
 [  75   29   -8   29  -62  -22   96  102  -41   62]]


In [32]:
A=np.random.randint(0,255,size=(10,10),dtype=np.uint8)
print(A)
A.astype(np.int8)
print(A)


[[ 76 183   4  77 176  26 146 182  16 164]
 [236 184   8 109 228   5 107  66 114 150]
 [ 78 185 215 111 240 134  42 197 166 179]
 [251 165 188 213   6 195 174  69 141 162]
 [148 231 157 192 136 151 121  98 140 170]
 [ 73 196  97  23  29 184  93  28 158 175]
 [199 233  42 160 229 170 202  94 107 159]
 [251 219 249  97   6 205   2  49 180  55]
 [201  10 208 144  35 151 210 218 210 161]
 [150  60  13 139  42  59 226 148 227 191]]
[[ 76 183   4  77 176  26 146 182  16 164]
 [236 184   8 109 228   5 107  66 114 150]
 [ 78 185 215 111 240 134  42 197 166 179]
 [251 165 188 213   6 195 174  69 141 162]
 [148 231 157 192 136 151 121  98 140 170]
 [ 73 196  97  23  29 184  93  28 158 175]
 [199 233  42 160 229 170 202  94 107 159]
 [251 219 249  97   6 205   2  49 180  55]
 [201  10 208 144  35 151 210 218 210 161]
 [150  60  13 139  42  59 226 148 227 191]]


In [47]:
import numpy as np

def format_array_as_hex(array, width, sign_extend=False):
    """
    格式化 numpy 数组为指定宽度的十六进制字符串，可选是否补符号位。

    Args:
        array (Union[np.ndarray, int, list]): 输入数组或单个整数
        width (int): 格式化宽度（例如 4 表示 `04x`）
        sign_extend (bool): 是否补符号位

    Returns:
        list[str]: 格式化后的十六进制字符串列表
    """
    # 将输入统一为 numpy 数组
    if not isinstance(array, np.ndarray):
        array = np.array(array)

    # 转为 int32 以方便统一处理符号和宽度
    array = array.astype(np.int32)

    # 最大值用于无符号范围调整
    max_value = 1 << (width * 4)  # width=4 表示16位

    if not sign_extend:
        # 无符号表示，负数转换为补码形式
        array = np.where(array < 0, array + max_value, array)
    else:
        # 补符号位（补码形式扩展）
        array = np.where(array < 0, array + max_value, array)

    # 将每个元素格式化为十六进制字符串
    hex_format = f"0{width}x"
    formatted_hex = [format(val, hex_format) for val in array]
    return formatted_hex

# 示例 1: 单个无符号数值
A = np.array([255], dtype=np.uint8)

# 示例 2: 混合正负数值
B = np.array([-1, 127, 128, 255], dtype=np.int16)

# 不补符号位
print("不补符号位 A:", format_array_as_hex(A, width=4, sign_extend=False))
print("不补符号位 B:", format_array_as_hex(B, width=4, sign_extend=False))

# 补符号位
print("补符号位 A:", format_array_as_hex(A, width=4, sign_extend=True))
print("补符号位 B:", format_array_as_hex(B, width=4, sign_extend=True))


不补符号位 A: ['00ff']
不补符号位 B: ['ffff', '007f', '0080', '00ff']
补符号位 A: ['00ff']
补符号位 B: ['ffff', '007f', '0080', '00ff']


In [63]:
import numpy as np

def decimal_to_twos_complement_extend(num, bit_width, target_width):
    """
    将十进制数转换为补码表示，并扩展符号位。
    
    参数:
    num: int，输入的十进制数
    bit_width: int，补码的位宽（原始宽度）
    target_width: int，扩展后的宽度
    
    返回:
    int，扩展后的补码表示
    """
    if bit_width > target_width:
        raise ValueError("目标宽度必须大于或等于原始宽度")
    
    # 计算模值
    mod = 2 ** bit_width
    extended_mod = 2 ** target_width
    
    # 转为补码
    if num < 0:
        num = (mod + num) % mod
    
    # 检查范围
    if num >= mod:
        raise ValueError("输入数字超出了给定位宽的表示范围")
    
    # 符号扩展
    if num & (1 << (bit_width - 1)):  # 如果最高位是1
        num = num | (extended_mod - mod)  # 符号扩展
    else:
        num = num & (mod - 1)  # 保留低位
    
    return num

# 测试
num = -120
bit_width = 8
target_width = 12
result = decimal_to_twos_complement_extend(num, bit_width, target_width)

print(f"十进制数 {num} 转换为 {bit_width}-位补码扩展到 {target_width}-位后的值为: {hex(result)}, 十进制为: {result}")


十进制数 -120 转换为 8-位补码扩展到 12-位后的值为: 0xf88, 十进制为: 3976


In [66]:
import numpy as np

def array_decimal_to_twos_complement_extend(arr, bit_width, target_width):
    """
    将 NumPy 数组中的十进制数转换为补码表示，并扩展符号位。

    参数:
    arr: np.ndarray，输入数组
    bit_width: int，原始位宽
    target_width: int，扩展后的位宽

    返回:
    np.ndarray，补码表示并符号扩展后的数组
    """
    if bit_width > target_width:
        raise ValueError("目标宽度必须大于或等于原始宽度")
    
    mod = 2 ** bit_width
    extended_mod = 2 ** target_width

    # 转换为补码（小于0的值直接映射补码表示）
    arr = np.where(arr < 0, mod + arr, arr)

    # 符号扩展（最高位为符号位）
    arr = np.where(arr & (1 << (bit_width - 1)), arr | (extended_mod - mod), arr)
    
    return arr

# 示例
arr = np.array([5, -5, 7, -7, -1, 0],dtype=np.int8)
bit_width = 8
target_width = 12

result = array_decimal_to_twos_complement_extend(arr, bit_width, target_width)
print(f"输入数组: {arr}")
print(f"符号扩展后的数组: {result}")


输入数组: [ 5 -5  7 -7 -1  0]
符号扩展后的数组: [   5 4091    7 4089 4095    0]


In [1]:
import numpy as np
np.random.seed(1)
print(type(np))  # 输出应该是 <class 'module'>，否则是变量覆盖问题
L1 = np.random.randn(3, 3)
L2 = np.random.randn(3, 3)
print(L1)
print(L2)

<class 'module'>
[[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]
 [ 1.74481176 -0.7612069   0.3190391 ]]
[[-0.24937038  1.46210794 -2.06014071]
 [-0.3224172  -0.38405435  1.13376944]
 [-1.09989127 -0.17242821 -0.87785842]]


In [30]:
print(format(123,"05x"))
3328*3

0007b


9984